trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
   - job: BuildFirstJob
     steps:
      - bash: echo build FirstJob
   - job: BuildSecondJob
     steps:
      - bash: echo build SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DevDeployJob
- stage: QADeploy
  dependsOn: 
   DevDeploy
   Build
  jobs:
    - job: QADeployJob
      steps:
      - bash: echo QADeployJob
- stage: ProdDeploy
  dependsOn: QADeploy
  jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo ProdDeployJob
