trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
 - stage: Build
   jobs:
   - job: BuildFirstJob
     steps:
      - bash: echo build FirstJob
   - job: BuildSecondJob
     steps:
      - bash: echo build SecondJob
 - stage: DevDeploy
   jobs:
    - job: DevDeployJob
      steps:
      - bash: echo DevDeployJob
 - stage: QADeploy
   jobs:
   - job: QADeployJob
     steps:
       - bash: echo QADeployJob
 - stage: ProdDeploy
   jobs:
   - job: ProdDeploy
     steps:
       - bash: echo ProdDeploy

